# --- Configuration principale ---
title: Kadri Mohamed | Data Analyst  
description: >-  
  Bienvenue sur mon portfolio professionnel.  
  Découvrez mes projets d'analyses de données, mes dashboards Power BI et mes visualisations interactives.  
baseurl: ""  # Laisser vide si le site est à la racine du dépôt
url: "https://kadri-mohamed.github.io"  # URL de ton site

# --- Thème et apparence ---
theme: jekyll-theme-cayman  
show_downloads: false  # Désactiver le bouton de téléchargement du dépôt
github:
  is_project_page: false  

# --- SEO et réseaux sociaux ---
author: Kadri Mohamed  
email: tonemail@example.com  
linkedin: https://linkedin.com/in/kadri-mohamed  
github_username: kadri-mohamed  
keywords: "Data Analyst, Power BI, Tableau de bord, Visualisation, Agroalimentaire"  
favicon: "/assets/favicon.ico"  # Icône du site (facultatif)

# --- Navigation (facultatif) ---
navbar_links:
  - name: À propos
    link: /#about  
  - name: Projets
    link: /#projects  
  - name: Contact
    link: /#contact  

# --- Plugins (facultatif) ---
plugins:
  - jekyll-feed  # Génère un flux RSS
  - jekyll-sitemap  # Crée automatiquement une sitemap.xml pour le SEO
  - jekyll-seo-tag  # Améliore le SEO de ton site

# --- Paramètres de pagination (si besoin) ---
paginate: 5  # Nombre d'articles par page
paginate_path: "/page:num/"

# --- Paramètres de langue ---
lang: fr  


